// Package launcher manages ~/.cepm/bin/cepm-host, the small shell script the
// native messaging manifest points at. Chrome only ever sees this one stable
// path; the script resolves the actual cepm binary, so upgrades via Homebrew,
// go install, mise, or plain file replacement never require touching Chrome's
// NativeMessagingHosts directory again.
package launcher

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/be-hase/cepm/internal/paths"
)

// shimCandidates returns known version-manager shim locations for cepm.
// Shims are stable across upgrades, so they serve as a fallback when the
// recorded binary path disappears (e.g. mise removed an old version dir).
func shimCandidates() []string {
	home, err := os.UserHomeDir()
	if err != nil {
		return nil
	}
	return []string{
		filepath.Join(home, ".local", "share", "mise", "shims", "cepm"),
		filepath.Join(home, ".asdf", "shims", "cepm"),
	}
}

// Install writes the launcher script recording execPath as the primary
// binary. Existing shims are added as fallbacks.
func Install(execPath string) error {
	path, err := paths.LauncherPath()
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	var fallback strings.Builder
	for _, shim := range shimCandidates() {
		if shim == execPath {
			continue
		}
		if _, err := os.Stat(shim); err == nil {
			fmt.Fprintf(&fallback, "[ -x \"$CEPM\" ] || CEPM=%q\n", shim)
		}
	}
	script := fmt.Sprintf(`#!/bin/sh
# Generated by cepm; do not edit. Chrome launches this as the cepm native
# messaging host. cepm rewrites it automatically when the binary moves.
CEPM=%q
%sexec "$CEPM" native-host "$@"
`, execPath, fallback.String())

	// Write atomically: Chrome may exec the script at any moment.
	tmp, err := os.CreateTemp(filepath.Dir(path), ".cepm-host-*")
	if err != nil {
		return err
	}
	defer os.Remove(tmp.Name())
	if _, err := tmp.WriteString(script); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Chmod(0o755); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	return os.Rename(tmp.Name(), path)
}

var recordedRe = regexp.MustCompile(`(?m)^CEPM="(.+)"$`)

// RecordedPath returns the primary binary path recorded in the launcher, or
// "" when the launcher does not exist.
func RecordedPath() (string, error) {
	path, err := paths.LauncherPath()
	if err != nil {
		return "", err
	}
	data, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		return "", nil
	}
	if err != nil {
		return "", err
	}
	m := recordedRe.FindSubmatch(data)
	if m == nil {
		return "", fmt.Errorf("launcher %s has an unexpected format (re-run cepm setup)", path)
	}
	return string(m[1]), nil
}

// SelfHeal rewrites the launcher when the currently running binary differs
// from the recorded one (e.g. after an upgrade that changed the install
// path). It is a silent no-op before setup has run and on any error: every
// CLI invocation calls this and must never be disturbed by it.
func SelfHeal() {
	recorded, err := RecordedPath()
	if err != nil || recorded == "" {
		return
	}
	exe, err := os.Executable()
	if err != nil || exe == recorded {
		return
	}
	_ = Install(exe)
}
