// Package launcher manages ~/.cepm/bin/cepm-host, the small shell script the
// native messaging manifest points at. Chrome only ever sees this one stable
// path; the script resolves the actual cepm binary, so upgrades via Homebrew,
// go install, mise, or plain file replacement never require touching Chrome's
// NativeMessagingHosts directory again.
package launcher

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/be-hase/cepm/internal/paths"
)

// shimCandidates returns known version-manager shim locations for cepm.
// Shims are stable across upgrades, so they serve as a fallback when the
// recorded binary path disappears (e.g. mise removed an old version dir).
func shimCandidates() []string {
	home, err := os.UserHomeDir()
	if err != nil {
		return nil
	}
	return []string{
		filepath.Join(home, ".local", "share", "mise", "shims", "cepm"),
		filepath.Join(home, ".asdf", "shims", "cepm"),
	}
}

// Install writes the launcher script recording execPath as the primary
// binary. Existing shims are added as fallbacks.
func Install(execPath string) error {
	path, err := paths.LauncherPath()
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	var fallback strings.Builder
	for _, shim := range shimCandidates() {
		if shim == execPath {
			continue
		}
		if _, err := os.Stat(shim); err == nil {
			fmt.Fprintf(&fallback, "[ -x \"$CEPM\" ] || CEPM=%s\n", shellQuote(shim))
		}
	}
	script := fmt.Sprintf(`#!/bin/sh
# Generated by cepm; do not edit. Chrome launches this as the cepm native
# messaging host. cepm rewrites it automatically when the binary moves.
CEPM=%s
%sexec "$CEPM" native-host "$@"
`, shellQuote(execPath), fallback.String())

	// Write atomically: Chrome may exec the script at any moment.
	tmp, err := os.CreateTemp(filepath.Dir(path), ".cepm-host-*")
	if err != nil {
		return err
	}
	defer os.Remove(tmp.Name())
	if _, err := tmp.WriteString(script); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Chmod(0o755); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	return os.Rename(tmp.Name(), path)
}

// shellQuote renders s as a single-quoted POSIX shell word. Go's %q is a Go
// string literal, not a shell one: it leaves $ and backticks alone, so a path
// containing them would be substituted — and executed — every time Chrome
// starts the host.
func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

// shellUnquote reverses shellQuote.
func shellUnquote(s string) (string, bool) {
	if len(s) < 2 || s[0] != '\'' || s[len(s)-1] != '\'' {
		return "", false
	}
	return strings.ReplaceAll(s[1:len(s)-1], `'\''`, "'"), true
}

var recordedRe = regexp.MustCompile(`(?m)^CEPM=(.+)$`)

// RecordedPath returns the primary binary path recorded in the launcher, or
// "" when the launcher does not exist.
func RecordedPath() (string, error) {
	path, err := paths.LauncherPath()
	if err != nil {
		return "", err
	}
	data, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		return "", nil
	}
	if err != nil {
		return "", err
	}
	m := recordedRe.FindSubmatch(data)
	if m == nil {
		return "", fmt.Errorf("launcher %s has an unexpected format (re-run cepm setup)", path)
	}
	recorded, ok := shellUnquote(string(m[1]))
	if !ok {
		return "", fmt.Errorf("launcher %s has an unexpected format (re-run cepm setup)", path)
	}
	return recorded, nil
}

// SelfHeal rewrites the launcher when the currently running binary differs
// from the recorded one (e.g. after an upgrade that changed the install
// path). It is a silent no-op before setup has run and on any error: every
// CLI invocation calls this and must never be disturbed by it.
func SelfHeal() {
	recorded, err := RecordedPath()
	if err != nil || recorded == "" {
		return
	}
	exe, err := os.Executable()
	if err != nil || exe == recorded {
		return
	}
	// "go run" and similar produce binaries under the temp dir that vanish
	// on exit; repointing the launcher at one strands Chrome until a durable
	// cepm runs again. Heal from such a binary only when the recorded one is
	// already gone — an ephemeral path beats a dangling one.
	if underDir(os.TempDir(), exe) {
		if _, err := os.Stat(recorded); err == nil {
			return
		}
	}
	_ = Install(exe)
}

// underDir reports whether path is inside dir.
func underDir(dir, path string) bool {
	rel, err := filepath.Rel(dir, path)
	return err == nil && rel != ".." && !strings.HasPrefix(rel, ".."+string(filepath.Separator))
}
